# Generated by Django 4.0.5 on 2023-01-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count',
            fields=[
                ('like', models.CharField(default=0, max_length=10)),
                ('dislike', models.CharField(default=0, max_length=12)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'count',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('pk1', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=1200)),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first.count', unique=True)),
            ],
            options={
                'db_table': 'entrys',
            },
        ),
    ]
